# -*- coding: utf-8 -*-
"""AIMLsession11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UpGORzJM_a_2vE0vTk2J89zrj4FMuWeP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score

df = pd.read_csv('iris.data',names=['sepal length','sepal width','petal length','petal width','class'])
df.head()

df.columns

X = df[['sepal length', 'sepal width', 'petal length', 'petal width']]
y = df['class']

X

scaler = StandardScaler()
X = scaler.fit_transform(X)

X

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

knn = KNeighborsClassifier(n_neighbors=3,metric='euclidian')
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

accuracy_score(y_pred,y_test)

test_data = np.array([[5.1,3.5,1.4,0.2]])

test_data = scaler.transform(test_data)

knn.predict(test_data)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor

df = pd.read_csv('auto-mpg.data',names=['mpg','cylinders','displacement','horsepower','weight','acceleration','model year','origin','car name'],delim_whitespace=True)

df.head()

df = df[df['horsepower'] != '?']

df.head()

df.columns

X = df[['cylinders', 'displacement', 'horsepower', 'weight','acceleration']]
y = df['mpg']

X = scaler.fit_transform(X)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

knnr = KNeighborsRegressor(n_neighbors=5)
knnr.fit(X_train,y_train)

knnr.score(X_test,y_test)

test_data = np.array([[8,307,130,3504,12]])

test_data = scaler.transform(test_data)

knnr.predict(test_data)

