# -*- coding: utf-8 -*-
"""AIMLSession9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k5G-OMqkvkwtQVOzNhyTQoi_13PEMZRC
"""

import pandas as pd
df = pd.DataFrame({'x':[0,1,2,3,4],'y':[1,3,5,7,9]})

df.head()

x = df[['x']]
y = df['y']

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x,y)

model.coef_

model.intercept_

print(f'f(x) = {int(model.coef_[0])} * x+{int(model.intercept_)}')

model.predict([[5]])

df = pd.read_csv('auto-mpg.data',names =['mpg','cylinders','displacement','horsepower','weight','acceleration','model_year','origin','car_name']
 ,delim_whitespace=True)

df.head()

df = df[df['horsepower'] != '?']

df.shape

#step1
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

#step 2
df = pd.read_csv('auto-mpg.data',names =['mpg','cylinders','displacement','horsepower','weight','acceleration','model_year','origin','car_name']
 ,delim_whitespace=True)

df = df[df['horsepower'] != '?']

df.columns

#step 3
X = df[['cylinders', 'displacement', 'horsepower', 'weight','acceleration', 'model_year', 'origin']]
y = df['mpg']

#step 4
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=131) #hyper parameter tuning

X_train.head()

#step 5
lr = LinearRegression()

#step 6
lr.fit(X_train,y_train)

lr.predict([[8	,307.0,	130.0,	3504.0,	12.0	,70,1]])

