# -*- coding: utf-8 -*-
"""AIMLsession10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPymrNeUrXqe-fs_zEVGNWZpXzhZyiXd
"""

from math import exp

1/(1+exp(-9))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score

df = pd.read_csv('iris.data',names=['sepal_length','sepal_width','petal_length','petal_width','class'])

df.head()

df.columns

X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['class']

X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=42) #Expected Question

lr = LogisticRegression()

lr.fit(X_train,y_train)

lr.score(X_train,y_train)

test_data = np.array([[5.1,3.5 ,1.4 ,0.2]])

lr.predict(test_data)

lr.predict_proba(test_data)

np.round(lr.predict_proba(test_data))

y_pred = lr.predict(X_test)

confusion_matrix(y_test,y_pred)

lr.score(X_test,y_test)

accuracy_score(y_test,y_pred)

