# -*- coding: utf-8 -*-
"""AIMLSession16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AVf9RbP-Lkn_z_CJBdFDuN2Bf6vchT1i
"""

import numpy as np
from sklearn.linear_model import Perceptron

X = np.array([[22],[34],[20],[25],[30],[35]])
y = np.array([0,1,0,0,1,1])

pct = Perceptron(max_iter=1000, eta0=0.1, random_state=42)
pct.fit(X,y)

pct.predict([[30]])

print('weights',pct.coef_)
print('bias',pct.intercept_)

from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

iris = load_iris()

X = iris.data
y = iris.target

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

pc = Perceptron(max_iter=1000,eta0=0.1,random_state=42)
pc.fit(X_train,y_train)

y_pred = pc.predict(X_test)

accuracy_score(y_test,y_pred)

